import { makeStyles } from "@material-ui/core";

const examPageStyles = makeStyles({
    introHead: {
        width: '680px',
        height: '44px',
        color: '#31456A',
        fontFamily: 'Montserrat',
        fontSize: '36px',
        fontStyle: 'normal',
        fontWeight: '800',
        lineHeight: '44px',
        letterSpacing: '0px',
        textAlign: 'center',
        display: 'flex',
        alignItems: 'center',
        position: "absolute",
        left: '380.09px',
        top: '201.32px',
    },
    partOfHead: {
        height: '44px',
        width: '124px',
        color: '#08C5A7',
        fontFamily: 'Montserrat',
        fontSize: '36px',
        fontStyle: 'normal',
        fontWeight: '800',
        lineHeight: '44px',
        letterSpacing: '0px',
        textAlign: 'center',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    introDes: {
        width: '274px',
        height: '51px',
        color: '#31456AB2',
        fontFamily: 'Montserrat',
        fontSize: '18px',
        fontStyle: 'normal',
        fontWeight: '400',
        lineHeight: '200%',
        letterSpacing: '0px',
        textAlign: 'center',
        display: 'flex',
        alignItems: 'center',
        position: "absolute",
        left: '583px',
        top: '259px',
    },
    jeeMains: {
        position: 'absolute',
        width: '170px',
        height: '56px',
        left: '320px',
        top: '345px',
    },
    jeeAdvance: {
        position: 'absolute',
        width: '170px',
        height: '56px',
        left: '530px',
        top: '345px',
    },
    custom: {
        position: 'absolute',
        width: '170px',
        height: '56px',
        left: '740px',
        top: '345px',
    },
    neet: {
        position: 'absolute',
        width: '170px',
        height: '56px',
        left: '950px',
        top: '345px',
    },
    allExams: {
        height: '30px',
        widht: '110px',
        position: 'absolute',
        left: '17.36%',
        right: '75%',
        top: '22.05%',
        bottom: '76.63%',
    },
    previousExams: {
        height: '30px',
        width: '160px',
        position: 'absolute',
        left: '27.78%',
        right: '61.11%',
        top: '22.05%',
        bottom: '76.63%'
    },
    currentExams: {
        height: '30px',
        width: '150px',
        position: 'absolute',
        left: '41.67%',
        right: '47.92%',
        top: '22.05%',
        bottom: '76.63%'
    },
    upcomingExams: {
        height: '30px',
        width: '180px',
        position: 'absolute',
        left: '54.86%',
        right: '32.64%',
        top: '22.05%',
        bottom: '76.63%'
    },
    firstExamCard: {
        width: '300px',
        height: '353px',
        position: 'absolute',
        left: '250px',
        top: '601px'
    }
});

export default examPageStyles;